// Random names generator
"use strict";

var SC = window.SC || {};

SC.randomSpaceCompany = function () {
    var movies = ["Yutani", "Wayland", "Liandri", "Zorg", "UAC"],
        greek = ["Alpha", "Beta", "Gamma", "Delta", "Epsilon", "Zeta", "Eta", "Theta", "Iota", "Kappa", "Lambda", "Mu", "Ni", "Xi", "Ommicron", "Pi", "Rho", "Sigma", "Tau", "Epsylon", "Phi", "Chi", "Psi", "Omega"],
        constelations = ["Andromeda", "Aquarius", "Aquila", "Ara", "Argo Navis", "Aries", "Auriga", "Boötes", "Cancer", "Canis Major", "Canis Minor", "Capricornus", "Cassiopeia", "Centaurus", "Cepheus", "Cetus", "Corona Australis", "Corona Borealis", "Corvus", "Crater", "Cygnus", "Delphinus", "Draco", "Equuleus", "Eridanus", "Gemini", "Hercules", "Hydra", "Leo", "Lepus", "Libra", "Lupus", "Lyra", "Ophiuchus", "Orion", "Pegasus", "Perseus", "Pisces", "Piscis Austrinus", "Sagitta", "Sagittarius", "Scorpius", "Serpens", "Taurus", "Triangulum", "Ursa Major", "Ursa Minor", "Virgo"],
        asteroids = ["Ceres", "Vesta", "Pallas", "Hygiea", "Interamnia", "Europa", "Davida", "Sylvia", "Cybele", "Eunomia", "Juno", "Euphrosyne", "Hektor", "Thisbe", "Bamberga", "Patientia", "Herculina", "Doris", "Ursula", "Camilla", "Eugenia", "Iris", "Amphitrite", "Diotima", "Fortuna", "Egeria", "Themis", "Aurora", "Alauda", "Hermione", "Aletheia", "Palma", "Nemesis", "Hebe", "Psyche", "Lachesis", "Daphne", "Metis"],
        moons = ["Ganymede", "Titan", "Callisto", "Io", "Moon", "Europa", "Triton", "Titania", "Rhea", "Oberon", "Iapetus", "Umbriel", "Ariel", "Dione", "Tethys", "Dysnomia", "Enceladus", "Miranda", "Proteus", "Mimas", "Nereid", "Hiʻiaka", "Hyperion", "Phoebe", "Larissa", "Janus", "Galatea", "Namaka", "Amalthea", "Puck", "Despina", "Sycorax", "Himalia", "Portia", "Caliban", "Thebe", "Juliet", "Prometheus", "Elara", "Thalassa", "Pandora", "Belinda", "Cressida", "Rosalind", "Naiad", "Desdemona", "Halimede", "Neso", "Pasiphae", "Prospero", "Bianca", "Setebos", "Carme", "Sao", "Laomedeia", "Metis", "Ophelia", "Psamathe", "Siarnaq", "Cordelia", "Sinope", "Lysithea", "Albiorix", "Helene", "Perdita", "Atlas", "Ananke", "Telesto", "Pan", "Paaliaq", "Phobos", "Leda", "Stephano", "Cupid", "Trinculo", "Ymir", "Calypso", "Kiviuq", "Adrastea", "Tarvos", "Ferdinand", "Francisco", "Ijiraq", "Mab", "Deimos", "Erriapus", "Margaret", "Hyrrokkin", "Skathi", "Callirrhoe", "Themisto", "Aegir", "Bebhionn", "Bergelmir", "Fornjot", "Greip", "Hati", "Jarnsaxa", "Loge", "Skoll", "Surtur", "Bestla", "Daphnis", "Kari", "Mundilfari", "Narvi", "Suttungr", "Tarqeq", "Thrymr", "Praxidike", "Fenrir", "Pallene", "Iocaste", "Kalyke", "Farbauti", "Taygete", "Harpalyke", "Aoede", "Autonoe", "Dia", "Eukelade", "Helike", "Hermippe", "Thyone", "Anthe", "Chaldene", "Isonoe", "Erinome", "Aitne", "Arche", "Carpo", "Euanthe", "Eurydome", "Hegemone", "Methone", "Polydeuces", "Cyllene", "Euporie", "Herse", "Kale", "Kallichore", "Kore", "Mneme", "Orthosie", "Pasithee", "Sponde", "Thelxinoe", "Valetudo", "Aegaeon"],
        stars = ["Achernar", "Albireo", "Alcor", "Alcyone", "Aldebaran", "Algol", "Alnilam", "Alnitak", "Alphard", "Alruba", "Altair", "Antares", "Arcturus", "Asterope", "Atlas", "Barnard", "Bellatrix", "Betelgeuse", "Canopus", "Capella", "Castor", "Celaeno", "Cor Caroli", "Deneb", "Denebola", "Electra", "Fomalhaut", "Hamal", "Maia", "Meissa", "Merope", "Mintaka", "Mira", "Mizar", "Pleione", "Polaris", "Pollux", "Procyon", "Proxima", "Regulus", "Rigel", "Saiph", "Sirius", "Spica", "Taygeta", "Thuban", "Vega", "Sirius", "Canopus", "Centauri", "Arcturus", "Vega", "Capella", "Rigel", "Procyon", "Achernar", "Betelgeuse", "Hadar", "Altair", "Acrux", "Aldebaran", "Antares", "Spica", "Pollux", "Fomalhaut", "Deneb", "Mimosa", "Regulus", "Adhara", "Shaula", "Castor", "Gacrux", "Bellatrix", "Elnath", "Miaplacidus", "Alnilam", "Regor", "Alnair", "Alioth", "Alnitak", "Dubhe", "Mirfak", "Wezen", "Sargas", "Kaus Australis", "Avior", "Alkaid", "Menkalinan", "Atria", "Alhena", "Peacock", "Alsephina", "Mirzam", "Alphard", "Polaris", "Hamal", "Algieba", "Diphda", "Mizar", "Nunki", "Menkent", "Mirach", "Alpheratz", "Rasalhague", "Kochab", "Saiph", "Denebola", "Algol", "Tiaki", "Muhlifain", "Aspidiske", "Suhail", "Alphecca", "Mintaka", "Sadr", "Eltanin", "Schedar", "Naos", "Almach", "Caph", "Izar", "Dschubba", "Larawag", "Merak", "Ankaa", "Girtab", "Enif", "Scheat", "Sabik", "Phecda", "Aludra", "Markeb", "Navi", "Markab", "Aljanah"],
        prefix = SC.randomItem((movies.join(",") + "," + greek.join(",") + "," + constelations.join(",") + "," + asteroids.join(",") + "," + moons.join(",") + "," + stars.join(",")).split(",")),
        suffix = SC.randomItem(["Mining Corp.", "Corps", "LLC", "Ltd.", "Inc.", "Transport", "Corporation", "Logistics", "Industries", "Group"]),
        pirate = SC.randomItem(["Resistance", "Band", "Bunch", "Group", "Killers", "Bandits", "Troopers", "Mercenaries", "Brave", "Intouchables", "Pirates", "Thiefs", "Assassins", "Siners", "Hoodlums", "Burglars", "Criminals", "Syndicate", "Muggers", "Pickpockets", "Robbers", "Burglars", "Swindlers", "Hunters", "Butchers", "Soldiers", "Legions", "Legionaries", "Comandos", "Fighters", "Guards", "Guerrilla", "Marines", "Veterans", "Recruits", "Warmongers", "Berets", "Soldiers", "Scouts", "Gunners", "Conscripts", "Cutthroats", "Survivors", "Apostoles", "Followers", "Believers"]);
    return prefix + " " + (Math.random() < 0.666 ? suffix : pirate)
};
